services:
  postgres:
    image: postgres:17
    container_name: balancebuddy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balancebuddy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: balancebuddy-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  server:
    build:
      context: ./server
    container_name: balancebuddy-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build:
      context: ./client
    container_name: balancebuddy-client
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
volumes:
  postgres_data:
  redis_data: